### ISSUE TITLE
Broke Create New List

### ISSUE THREAD

**Issue by chriswininger** [infinite-industries/infinite-old-api-server#2]
Creating a new list in the developer branch gives the error

TypeError: Cannot read property 'create' of undefined
    at Object.addList (/Users/chris/projects/infinite/controllers/users.js:27:32)
    at /Users/chris/projects/infinite/routes/users.js:26:19
    at Layer.handle [as handle_request] (/Users/chris/projects/infinite/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/chris/projects/infinite/node_modules/express/lib/router/route.js:137:13)

This is a regression caused by postgress migration. I think probably it's some code that can be removed but I'll need to look ait.

**Comment by chriswininger** [comment]
fixed by commit 4083e226e5ac433994882bb8b21904faba36fe4b (which references the wrong issue #)
